### ISSUE TITLE
no color

### ISSUE THREAD

**Issue by chronoss09** [supergamerguy777/Bugs-Bunny-Crazy-Castle-2-DX-backup-#1]
hi

I apply the first patch and the fix but the game is always on black/white...

![Capture](https://user-images.githubusercontent.com/17669980/235569818-9cce1b7a-fe70-49ba-904b-9c40649f6892.PNG)

**Comment by supergamerguy777** [comment]
Only the main levels have been colorized here. It works just fine for me after getting past the title screen and intro.

![image](https://user-images.githubusercontent.com/125148764/235683886-34d4eded-654c-497d-a98f-37500e10fe1e.png)
